mod basic_material_instance;
mod basic_material_properties;
mod compound_material_instance;
mod compound_material_properties;
mod material_instance;
mod material_manager;
mod material_properties;
mod materials_plugin;
mod thermal_properties;

pub use self::basic_material_instance::BasicMaterialInstance;
pub use self::basic_material_properties::BasicMaterialProperties;
pub use self::compound_material_instance::CompoundMaterialInstance;
pub use self::compound_material_properties::ComposingMaterial;
pub use self::compound_material_properties::CompoundMaterialProperties;
pub use self::material_instance::MaterialInstance;
pub use self::material_manager::MaterialID;
pub use self::material_manager::MaterialManager;
pub use self::material_properties::MaterialProperties;
pub use self::materials_plugin::MaterialConfigs;
pub use self::materials_plugin::MaterialsPlugin;
pub use self::thermal_properties::ThermalProperties;
